FreeBSD_task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  env:
    ASSUME_ALWAYS_YES: TRUE # required for unattended "pkg" invocation
  install_script:
    - pkg install git cmake pkgconf ccache
      fftw3 fftw3-float libsndfile qt5 qt5-x11extras
      pulseaudio portaudio jackit sdl2
      fluidsynth stk libgig Carla
  prepare_script:
    - git submodule update --init --recursive
  build_script:
    - mkdir build && cd build
    - cmake .. -DWANT_QT5=ON -DUSE_CCACHE=ON -DCMAKE_PREFIX_PATH=/usr/local
    - make -j4
  pkg_cache:
    folder: /var/cache/pkg
  ccache_cache:
    folder: $HOME/.ccache
