language: cpp
compiler: gcc
dist: trusty
sudo: required
cache:
    directories:
        - $HOME/apt_mingw_cache
        - $HOME/.ccache
        - $HOME/pbuilder-bases
matrix:
    include:
        - env: TARGET_OS=win32 QT5=True
        - env: TARGET_OS=win64 QT5=True
        - env: QT5=True
        - os: osx
          osx_image: xcode9.4
          env: QT5=True
before_install:
   - . ${TRAVIS_BUILD_DIR}/.travis/${TRAVIS_OS_NAME}.${TARGET_OS}.before_install.sh
install:
    - . ${TRAVIS_BUILD_DIR}/.travis/${TRAVIS_OS_NAME}.${TARGET_OS}.install.sh
before_script:
    - export CMAKE_FLAGS="-DWANT_QT5=$QT5 -DCMAKE_BUILD_TYPE=RelWithDebInfo"
script:
    - . ${TRAVIS_BUILD_DIR}/.travis/${TRAVIS_OS_NAME}.${TARGET_OS}.script.sh
